Conditions if...else
tejasparadkar/JSLearn pull request #2
Opened 2022-12-20 15:07 UTC by tejasparadkar

2022-12-20 15:47 UTC, magharkar commented on conditions.js
> +    else if (x > 1 && x < 21 )
Handle the case for x = 1

2022-12-20 15:48 UTC, magharkar requested changes
Add the task in a specific folder of its own.

2022-12-20 18:08 UTC, tejasparadkar commented on conditions.js
> +    else if (x > 1 && x < 21 )
case handled and updated

2022-12-21 02:21 UTC, magharkar approved these changes

2022-12-21 02:40 UTC, merged